### ISSUE TITLE
Some questions about Vimeo-90K-T for 4×

### ISSUE THREAD

**Issue by ZhangDY827** [wh1h/DNLN#1]
Hello, thank your for your source code. I have a question on TABLE 3 in your paper.  The Vimeo-90K-T dataset is divied into 3 parts  according to the motion velocity, slow, medium and fast.  I have downloaded the file 'vimeo_super_resolution_test', in sep_testlist.txt, I want to konw a specific clip is corresponding to which groups (slow, medium and fast). Do you have a file which records the classification of each clip.

**Comment by wh1h** [comment]
https://github.com/alterzero/RBPN-PyTorch/tree/master/vimeo90k
The group files can be downloaded from this link .

**Comment by ZhangDY827** [comment]
谢谢，我去年就在arxiv上看到这篇文章，我觉得这篇文章配得上cvpr的水平。我一直以为这是投了cvpr2020的文章，为什么投了IEEE ACCESS呢😌------------------ 原始邮件 ------------------
发件人: "wh1h"<notifications@github.com>
发送时间: 2020年1月6日(星期一) 晚上9:31
收件人: "wh1h/DNLN"<DNLN@noreply.github.com>;
抄送: "ZhangDY"<1725375269@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [wh1h/DNLN] Some questions about Vimeo-90K-T for 4× (#1)



https://github.com/alterzero/RBPN-PyTorch/tree/master/vimeo90k
 The group files can be downloaded from this link .
 
&mdash;
